spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&useSSL=false
